pcl:
	glslViewer pcl.ply pcl.vert pcl.frag iphone_depth.jpeg -e camera_position,0.8877,-0.228562,-1.34835 -l

pcl_poisson_fill:
	glslViewer pcl.ply pcl.vert pcl_poisson_fill.frag iphone_depth.jpeg -e camera_position,0.8877,-0.228562,-1.34835 -l

stars:
	glslViewer pcl.ply stars.vert pcl.frag -l 

stars_trail:
	glslViewer pcl.ply stars.vert pcl_trail.frag -l 

gpgpu:
	glslViewer pcl.ply gpgpu.vert gpgpu.frag -e buffers,on -l 