pcl:
	glslViewer pcl.vert pcl.frag iphone_depth.jpeg -e pcl_plane -e camera_position,-0.625535,0.167038,1.78034 -l

pcl_poisson_fill:
	glslViewer pcl.vert pcl_poisson_fill.frag iphone_depth.jpeg -e pcl_plane -e camera_position,-0.625535,0.167038,1.78034 -l

stars:
	glslViewer pcl.ply stars.vert pcl.frag -l 

stars_trail:
	glslViewer pcl.ply stars.vert pcl_trail.frag -l 

gpgpu:
	glslViewer gpgpu.vert gpgpu.frag -e pcl_plane -e buffers,on -e camera_position,-3.54947,-0.200495,-10.9241 -l 

physarum:
	glslViewer physarum.vert physarum.frag -e pcl_plane -l 