00_gooch:
	glslViewer 00_gooch.frag head.ply -l

00_gooch_quilt:
	glslViewer 00_gooch.frag head.ply --quilt 0

00_gooch_lenticular:
	glslViewer 00_gooch.frag head.ply --lenticular

01_shadows:
	glslViewer 01_shadows.frag head.ply -l

01_shadows_quilt:
	glslViewer 01_shadows.frag head.ply --quilt 0

01_shadows_lenticular:
	glslViewer 01_shadows.frag head.ply --lenticular

02_cubemap:
	glslViewer 02_cubemap.frag head.ply -C uffizi_cross.hdr -l

02_cubemap_quilt:
	glslViewer 02_cubemap.frag head.ply -C uffizi_cross.hdr --quilt 0

02_cubemap_lenticular:
	glslViewer 02_cubemap.frag head.ply -C uffizi_cross.hdr --lenticular

03_spherical_harmmonics:
	glslViewer 03_spherical_harmonics.frag head.ply -C uffizi_cross.hdr -l

03_spherical_harmmonics_quilt:
	glslViewer 03_spherical_harmonics.frag head.ply -C uffizi_cross.hdr --quilt 0

03_spherical_harmmonics_lenticular:
	glslViewer 03_spherical_harmonics.frag head.ply -C uffizi_cross.hdr --lenticular

04_fresnel:
	glslViewer 04_fresnel.vert 04_fresnel.frag head.ply -C uffizi_cross.hdr -l

04_fresnel_quilt:
	glslViewer 04_fresnel.vert 04_fresnel.frag head.ply -C uffizi_cross.hdr --quilt 0

04_fresnel_lenticular:
	glslViewer 04_fresnel.vert 04_fresnel.frag head.ply -C uffizi_cross.hdr --lenticular

05_ssao:
	glslViewer 05_ssao.frag head.ply -l
