00_gooch:
	glslViewer 00_gooch.frag head.ply -l

00_gooch_holoplay:
	glslViewer 00_gooch.frag head.ply --holoplay 1

01_shadows:
	glslViewer 01_shadows.frag head.ply -l

01_shadows_holoplay:
	glslViewer 01_shadows.frag head.ply --holoplay 1

02_cubemap:
	glslViewer 02_cubemap.frag head.ply -C uffizi_cross.hdr -l

02_cubemap_holoplay:
	glslViewer 02_cubemap.frag head.ply -C uffizi_cross.hdr --holoplay 1

03_spherical_harmmonics:
	glslViewer 03_spherical_harmonics.frag head.ply -C uffizi_cross.hdr -l

03_spherical_harmmonics_holoplay:
	glslViewer 03_spherical_harmonics.frag head.ply -C uffizi_cross.hdr --holoplay 1

04_fresnel:
	glslViewer 04_fresnel.vert 04_fresnel.frag head.ply -C uffizi_cross.hdr -l

04_fresnel_holoplay:
	glslViewer 04_fresnel.vert 04_fresnel.frag head.ply -C uffizi_cross.hdr --holoplay 1