NAME = $(GLEW_NAME)
CC = gcc
LD = ld
CFLAGS.EXTRA = -I/usr/openwin/include -fPIC
LDFLAGS.SO = -G
LDFLAGS.EXTRA = -L/usr/openwin/lib
LDFLAGS.GL = -lGL -lX11
NAME = GLEW
BIN.SUFFIX =
POPT = -O2
LIB.SONAME    = lib$(NAME).so.$(SO_MAJOR)
LIB.DEVLNK    = lib$(NAME).so
LIB.SHARED    = lib$(NAME).so.$(SO_VERSION)
LIB.STATIC    = lib$(NAME).a
LDFLAGS.SO    = -shared -Wl,-soname=$(LIB.SONAME)
