poisson_fill:
	glslViewer poisson_fill.frag flower.png -l

poisson_fill_visualize:
	glslViewer poisson_fill_visualize.frag flower.png -e buffers,on -l

laplacian_integrator:
	glslViewer laplacian_integrator.frag chart.png -l

poisson_blend:
	glslViewer poisson_blend.frag --u_target target.png --u_source source.jpg --u_source_mask source_mask.png -l

poisson_clone:
	glslViewer poisson_clone.frag --u_target target.png --u_source source.jpg --u_source_mask source_mask.png -l
