visualize:
	glslViewer visualize.frag flower.png -e buffers,on -l

poisson_fill:
	glslViewer poisson_fill.frag flower.png -l

poisson_blend:
	glslViewer poisson_blend.frag --u_target target.png --u_source source.jpg --u_source_mask source_mask.png -l

reconstruct:
	glslViewer reconstruct.frag chart.png -l
