poisson_fill:
	glslViewer poisson_fill.frag un_poisson.png -l

poisson_blend:
	glslViewer poisson_blend.frag --u_target target.jpg --u_source source.jpg --u_mask mask.png -l

reconstruct:
	glslViewer reconstruct.frag chart.png -l
