00_background:
	glslViewer 00_background.frag head.ply -l

00_background_holoplay:
	glslViewer 00_background.frag head.ply --holoplay 1

01_postprocessing:
	glslViewer 01_postprocessing.frag head.ply -l