00_background:
	glslViewer 00_background.frag head.ply -l

00_background_quilt:
	glslViewer 00_background.frag head.ply --quilt 0

00_background_lenticular:
	glslViewer 00_background.frag head.ply --lenticular
	
01_postprocessing:
	glslViewer 01_postprocessing.frag head.ply -l

02_depth:
	glslViewer 02_depth.frag head.ply -e debug,on -l